### ISSUE TITLE
Hoe de relatie tussen een Organisatie en een Agent van andere Organisatie voorstellen?

### ISSUE THREAD

**Issue by mielvds** [Informatievlaanderen/OSLO-Standaarden#114]
Is er een manier - met Organisatie Basis of andere APs -  om een Agent die een Positie houdt in een Organisatie te relateren aan een andere andere organisatie omdat ze bv. een account manager zijn?

```
:Bob a foaf:Person.

:orgA a org:Organization.
:orgB a org:Organization.

:AccountManagerOrgB a org:Post.
    org:postIn :orgA;
    org:hasRole :AccountManager;
    org:heldBy :Bob.

:AccountManagerOrgB ex:responsibleFor?? :OrgB.

```

**Comment by bertvannuffelen** [comment]
@mielvds eerst een organisatorische opmerking: kan je zulke domein vragen ofwel in de specifieke repo van de standaard stellen https://github.com/Informatievlaanderen/OSLOthema-organisatie of op de algemene vraag plek https://github.com/Informatievlaanderen/OSLO-Discussion/?

Dan kort op je vraag:
ja een persoon kan meerdere posities (https://data.vlaanderen.be/doc/applicatieprofiel/organisatie-basis/#Positie)  hebben per organisatie, maar ook verschillende posities opnemen bij verschillende organisaties.
Wat wel niet te adviseren is dat is de notie rol (http://www.w3.org/ns/org#Role) te verheffen tot positie.  (wat je ook niet gedaan hebt in het voorbeeld, maar wat we snel doen in ons taalgebruik.)

Een positie is gekoppeld aan een organisatie. Dus zowel orgA als orgB hebben de positie accountmanager met als generieke rol accountmanager. Dus
```
:Bob a foaf:Person.

:orgA a org:Organization.
:orgB a org:Organization.

:AccountManagerOrgA a org:Post.
    org:postIn :orgA;
    org:hasRole :AccountManager;
    org:heldBy :Bob.

:AccountManagerOrgB 
   org:postIn :orgB;
    org:hasRole :AccountManager;
    org:heldBy :Bob.
```

Hoe je het ook draait en keert een positie die gekoppeld is aan 2 organisaties is complex. Want formeel zal elke organisatie zijn goedkeuring moeten geven aan deze constructie (onafhankelijk van elkaar). En dus zijn dat 2 onafhankelijke posities die uitgeoefend worden door dezelfde persoon. Op moment dat er dus problemen ontstaan waarbij een van de partijen het akkoord  
opzegt dan zal dat weer uitgesplitst worden. Hoewel organisatie-basis dit niet verbiedt, ben ik van mening dat dus je naar het onderhoud en de evolutie in de data moet kijken voordat je deze synergie gaat uitdrukken. Het splitsen van informatie is altijd een complex geval.  

Wat bijkomend hierbij een uitdaging vormt is dat door de GDPR de synergie mogelijks niet kan worden gerealiseerd omdat een uniforme persoonsidentiteit niet publiek mag gemaakt worden. Dus `Bob` in het voorbeeld zou dus moeten 2 verschillende identificatoren met dezelfde naam en familienaam moeten zijn. Zulke afwegingen zijn buiten het model, maar kunnen in de praktijk een verschil maken tussen publieke informatiestructuren en interne informatiestructuren.

**Comment by mielvds** [comment]
> @mielvds eerst een organisatorische opmerking: kan je zulke domein vragen ofwel in de specifieke repo van de standaard stellen https://github.com/Informatievlaanderen/OSLOthema-organisatie of op de algemene vraag plek https://github.com/Informatievlaanderen/OSLO-Discussion/?

Done! Zie https://github.com/Informatievlaanderen/OSLOthema-organisatie/issues/3 (sorry, ik geraak soms de weg kwijt in de OSLO repos :))
