### ISSUE TITLE
Filter op homepagina werkt niet meer

### ISSUE THREAD

**Issue by jensscheerlinck** [Informatievlaanderen/OSLO-Standaarden#55]
De dropdown "Filter standaarden" werkt niet meer op https://data.vlaanderen.be/standaarden/

**Comment by KevinHaleydt** [comment]
thx @jensscheerlinck, zelfde issue eveneens op test.data.vlaanderen.

ik kijk het na

**Comment by KevinHaleydt** [comment]
Issue opgelost </script> tag ontbrak ergens in de html.

Ok op test.vlaanderen
